In [1]:
import os
os.environ['KAGGLE_USERNAME']='dinesh223344'
os.environ['KAGGLE_KEY']='KGAT_4f293546a7b4700c41008b912382b767'

In [2]:
!kaggle datasets download -d 'imtkaggleteam/netflix'

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/imtkaggleteam/netflix
License(s): other
Downloading netflix.zip to /content
100% 1.17M/1.17M [00:00<00:00, 118MB/s]

In [3]:
import pandas as pd
df=pd.read_csv('/content/netflix.zip')

In [4]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,143,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,90,Comedies,New NFL star Thad buys his old teammates' belo...
4,s1001,TV Show,Blue Planet II,NaN,David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,1,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...

In [5]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
7782,s995,TV Show,Blown Away,NaN,NaN,Canada,12-Jul-19,2019,TV-14,1,"International TV Shows, Reality TV",Ten master artists turn up the heat in glassbl...
7783,s996,TV Show,Blue Exorcist,NaN,"Nobuhiko Okamoto, Jun Fukuyama, Kana Hanazawa,...",Japan,1-Sep-20,2017,TV-MA,2,"Anime Series, International TV Shows",Determined to throw off the curse of being Sat...
7784,s997,Movie,Blue Is the Warmest Color,Abdellatif Kechiche,"Léa Seydoux, Adèle Exarchopoulos, Salim Kechio...","France, Belgium, Spain",26-Aug-16,2013,NC-17,180,"Dramas, Independent Movies, International Movies","Determined to fall in love, 15-year-old Adele ..."
7785,s998,Movie,Blue Jasmine,Woody Allen,"Cate Blanchett, Sally Hawkins, Alec Baldwin, L...",United States,8-Mar-19,2013,PG-13,98,"Comedies, Dramas, Independent Movies",The high life leads to high anxiety for a fash...
7786,s999,Movie,Blue Jay,Alex Lehmann,"Sarah Paulson, Mark Duplass, Clu Gulager",United States,6-Dec-16,2016,TV-MA,81,"Dramas, Independent Movies, Romantic Movies",Two former high school sweethearts unexpectedl...

In [6]:
df.describe()

       release_year     duration
count   7787.000000  7787.000000
mean    2013.932580    69.122769
std        8.757395    50.950743
min     1925.000000     1.000000
25%     2013.000000     2.000000
50%     2017.000000    88.000000
75%     2018.000000   106.000000
max     2021.000000   312.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   int64
 10  genres        7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(2), object(10)
memory usage: 730.2+ KB

In [8]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
genres             0
description        0
dtype: int64

In [9]:
df.drop('duration',axis=1,inplace=True)

In [10]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,Comedies,New NFL star Thad buys his old teammates' belo...
4,s1001,TV Show,Blue Planet II,NaN,David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...

In [11]:
df.drop('description',axis=1,inplace=True)

In [12]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,"International TV Shows, TV Dramas, TV Sci-Fi &..."
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,"Horror Movies, International Movies, Thrillers"
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,"Dramas, International Movies, Sports Movies"
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,Comedies
4,s1001,TV Show,Blue Planet II,NaN,David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,"British TV Shows, Docuseries, Science & Nature TV"

In [13]:
df['rating'].unique()

array(['TV-MA', 'TV-PG', 'R', 'TV-G', 'PG-13', 'TV-14', 'TV-Y', 'PG',
       'TV-Y7', 'NR', 'G', 'TV-Y7-FV', nan, 'UR', 'NC-17'], dtype=object)

In [14]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
genres             0
dtype: int64

In [15]:
df['rating']=df['rating'].fillna(df['rating'].mode()[0])

In [16]:
df['country']=df['country'].fillna(df['country'].mode()[0])

In [17]:
df['director']=df['director'].fillna(df['director'].mode()[0])

In [18]:
df['cast']=df['cast'].fillna(df['cast'].mode()[0])

In [19]:
df.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           0
genres           0
dtype: int64

In [20]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres
0,s1,TV Show,3%,"Raúl Campos, Jan Suter","João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,"International TV Shows, TV Dramas, TV Sci-Fi &..."
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,"Horror Movies, International Movies, Thrillers"
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,"Dramas, International Movies, Sports Movies"
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,Comedies
4,s1001,TV Show,Blue Planet II,"Raúl Campos, Jan Suter",David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,"British TV Shows, Docuseries, Science & Nature TV"

In [21]:
df['date_added']=df['date_added'].fillna(df['date_added'].mode()[0])

In [22]:
df['overall_year']=2026-df['release_year']

In [23]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres,overall_year
0,s1,TV Show,3%,"Raúl Campos, Jan Suter","João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,"International TV Shows, TV Dramas, TV Sci-Fi &...",6
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,"Horror Movies, International Movies, Thrillers",18
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,"Dramas, International Movies, Sports Movies",10
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,Comedies,10
4,s1001,TV Show,Blue Planet II,"Raúl Campos, Jan Suter",David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,"British TV Shows, Docuseries, Science & Nature TV",9

In [24]:
df['rating'].unique()

array(['TV-MA', 'TV-PG', 'R', 'TV-G', 'PG-13', 'TV-14', 'TV-Y', 'PG',
       'TV-Y7', 'NR', 'G', 'TV-Y7-FV', 'UR', 'NC-17'], dtype=object)

In [25]:
df['numeric_rating']=df['rating'].replace({'TV-MA':1,'TV-PG':2,'R':3,'TV-G':4,'PG-13':5,'TV-14':6,'TV-Y':7,'PG':8,'TV-Y7':9,'NR':10,'G':11,'TV-Y7-FV':12,'UR':13,'NC-17':14})

/tmp/ipykernel_6354/2626285237.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['numeric_rating']=df['rating'].replace({'TV-MA':1,'TV-PG':2,'R':3,'TV-G':4,'PG-13':5,'TV-14':6,'TV-Y':7,'PG':8,'TV-Y7':9,'NR':10,'G':11,'TV-Y7-FV':12,'UR':13,'NC-17':14})

In [26]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,genres,overall_year,numeric_rating
0,s1,TV Show,3%,"Raúl Campos, Jan Suter","João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,"International TV Shows, TV Dramas, TV Sci-Fi &...",6,1
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,"Horror Movies, International Movies, Thrillers",18,1
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,"Dramas, International Movies, Sports Movies",10,2
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,Comedies,10,3
4,s1001,TV Show,Blue Planet II,"Raúl Campos, Jan Suter",David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,"British TV Shows, Docuseries, Science & Nature TV",9,4

In [27]:

Q1 = df['numeric_rating'].quantile(0.25)
Q3 = df['numeric_rating'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['numeric_rating'] < lower_bound) | (df['numeric_rating'] > upper_bound)]
clean_df = df[(df['numeric_rating'] >= lower_bound) & (df['numeric_rating'] <= upper_bound)]

print("Outliers:")
print(outliers)

print(clean_df)

Outliers:
     show_id   type                      title                director  \
2800   s3519  Movie                  Lady-Like  Raúl Campos, Jan Suter
5486   s5937  Movie        Swearnet: The Movie        Warren P. Sonoda
7784    s997  Movie  Blue Is the Warmest Color     Abdellatif Kechiche

                                                   cast  \
2800  Allie Gallerani, Beverly D'Angelo, Olivia Lucc...
5486  Mike Smith, John Paul Tremblay, Robb Wells, Pa...
7784  Léa Seydoux, Adèle Exarchopoulos, Salim Kechio...

                     country date_added  release_year rating  \
2800           United States  18-Jan-19          2018  NC-17
5486                  Canada  24-Sep-17          2014  NC-17
7784  France, Belgium, Spain  26-Aug-16          2013  NC-17

                                                genres  overall_year  \
2800                      Comedies, Independent Movies             8
5486                    Comedies, International Movies            12
7784  Dramas, Independent Movies, International Movies            13

      numeric_rating
2800              14
5486              14
7784              14
     show_id     type                                      title  \
0         s1  TV Show                                         3%
1        s10    Movie                                       1920
2       s100    Movie                                 3 Heroines
3      s1000    Movie  Blue Mountain State: The Rise of Thadland
4      s1001  TV Show                             Blue Planet II
...      ...      ...                                        ...
7781    s994    Movie                                       Blow
7782    s995  TV Show                                 Blown Away
7783    s996  TV Show                              Blue Exorcist
7785    s998    Movie                               Blue Jasmine
7786    s999    Movie                                   Blue Jay

                    director  \
0     Raúl Campos, Jan Suter
1               Vikram Bhatt
2             Iman Brotoseno
3               Lev L. Spiro
4     Raúl Campos, Jan Suter
...                      ...
7781               Ted Demme
7782  Raúl Campos, Jan Suter
7783  Raúl Campos, Jan Suter
7785             Woody Allen
7786            Alex Lehmann

                                                   cast         country  \
0     João Miguel, Bianca Comparato, Michel Gomes, R...          Brazil
1     Rajneesh Duggal, Adah Sharma, Indraneil Sengup...           India
2     Reza Rahadian, Bunga Citra Lestari, Tara Basro...       Indonesia
3     Alan Ritchson, Darin Brooks, James Cade, Rob R...   United States
4                                    David Attenborough  United Kingdom
...                                                 ...             ...
7781  Johnny Depp, Penélope Cruz, Franka Potente, Ra...   United States
7782                                 David Attenborough          Canada
7783  Nobuhiko Okamoto, Jun Fukuyama, Kana Hanazawa,...           Japan
7785  Cate Blanchett, Sally Hawkins, Alec Baldwin, L...   United States
7786           Sarah Paulson, Mark Duplass, Clu Gulager   United States

     date_added  release_year rating  \
0     14-Aug-20          2020  TV-MA
1     15-Dec-17          2008  TV-MA
2      5-Jan-19          2016  TV-PG
3      1-Mar-16          2016      R
4      3-Dec-18          2017   TV-G
...         ...           ...    ...
7781   1-Oct-19          2001      R
7782  12-Jul-19          2019  TV-14
7783   1-Sep-20          2017  TV-MA
7785   8-Mar-19          2013  PG-13
7786   6-Dec-16          2016  TV-MA

                                                 genres  overall_year  \
0     International TV Shows, TV Dramas, TV Sci-Fi &...             6
1        Horror Movies, International Movies, Thrillers            18
2           Dramas, International Movies, Sports Movies            10
3                                              Comedies            10
4     British TV Shows, Docuseries, Science & Nature TV             9
...                                                 ...           ...
7781                                             Dramas            25
7782                 International TV Shows, Reality TV             7
7783               Anime Series, International TV Shows             9
7785               Comedies, Dramas, Independent Movies            13
7786        Dramas, Independent Movies, Romantic Movies            10

      numeric_rating
0                  1
1                  1
2                  2
3                  3
4                  4
...              ...
7781               3
7782               6
7783               1
7785               5
7786               1

[7784 rows x 12 columns]

In [28]:
x=df.drop(['rating'],axis=1)
y=df['rating']

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [30]:
x = pd.get_dummies(x,drop_first=True)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=82)
X_train=scaler.fit_transform(x_train)
X_test=scaler.transform(x_test)
x.head()

,release_year,overall_year,numeric_rating,show_id_s10,show_id_s100,show_id_s1000,show_id_s1001,show_id_s1002,show_id_s1003,show_id_s1004,...,"genres_TV Dramas, TV Sci-Fi & Fantasy, Teen TV Shows","genres_TV Dramas, TV Thrillers","genres_TV Dramas, Teen TV Shows","genres_TV Horror, TV Mysteries, TV Sci-Fi & Fantasy","genres_TV Horror, TV Mysteries, TV Thrillers","genres_TV Horror, TV Mysteries, Teen TV Shows","genres_TV Horror, Teen TV Shows","genres_TV Sci-Fi & Fantasy, TV Thrillers",genres_TV Shows,genres_Thrillers
0,2020,6,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2008,18,1,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2016,10,2,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,2016,10,3,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,2017,9,4,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [31]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [32]:
model=DecisionTreeClassifier()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
accuracy_score(y_test,y_pred)

1.0

In [33]:
model.score(X_test,y_test)

1.0

In [34]:
from sklearn.ensemble import RandomForestClassifier
model1=RandomForestClassifier()
model1.fit(X_train,y_train)

RandomForestClassifier()

In [35]:
accuracy_score(y_test,y_pred)

1.0

In [36]:
model1.score(X_test,y_test)

0.8552166934189406

In [40]:
import pickle
with open('model1.pkl','wb') as f:
  pickle.dump(model1,f)
from google.colab import files
files.download('model1.pkl')